#!/bin/bash

# Set the GOPATH to the local bin area
EXT=`pwd`/ext
GOPATH=$EXT:`pwd`

go get "github.com/skelterjohn/rerun"

# Build the server
go install ./...

$EXT/bin/rerun --build view/example/$1
